name: "Build and Deploy"

on:
  push:
    branches: ["master"]
  pull_request:

permissions:
  id-token: write
  contents: read

env:
  AZURE_FUNCTIONAPP_NAME: api-dev-function-app
  AZURE_FUNCTIONAPP_PACKAGE_PATH: src/AzureFunction/published
  CONFIGURATION: Release
  DOTNET_VERSION: 8.0.x
  WORKING_DIRECTORY: src/AzureFunction
  STORAGE_ACCOUNT: ${{ vars.AZ_STORAGE_ACCOUNT }}
  CONTAINER_NAME: ${{ vars.AZ_CONTAINER_NAME }}
  RESOURCE_GROUP: ${{ vars.AZ_RESOURCE_GROUP }}
  TF_VARS: ${{ vars.TF_VARS }}
  TF_VAR_AGENT_CLIENT_ID: ${{ secrets.TF_VAR_AGENT_CLIENT_ID }}
  TF_VAR_AGENT_CLIENT_SECRET: ${{ secrets.TF_VAR_AGENT_CLIENT_SECRET }}
  TF_VAR_SUBSCRIPTION_ID: ${{ secrets.TF_VAR_SUBSCRIPTION_ID }}
  TF_VAR_TENANT_ID: ${{ secrets.TF_VAR_TENANT_ID }}
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    needs:
      - terraform
    steps:
      - uses: actions/checkout@v4

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v3
        with:
          include-prerelease: True
          dotnet-version: ${{ env.DOTNET_CORE_VERSION }}

      - name: Restore
        run: dotnet restore "${{ env.WORKING_DIRECTORY }}"

      - name: Build
        run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore

      - name: Publish
        run: dotnet publish "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}"

      - name: Publish Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: functionapp
          path: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: functionapp
          path: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

      - name: "Login via Azure CLI"
        run: az login --service-principal --tenant ${{ env.TF_VAR_TENANT_ID }} --username ${{ env.TF_VAR_AGENT_CLIENT_ID }} --password ${{ env.TF_VAR_AGENT_CLIENT_SECRET }}

      - name: Deploy to Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          publish-profile: ${{ secrets.API_DEV_FUNCTION_APP_DFB2 }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
